services:
  backend:
    build: 
      context: ./desafio_techlead_back
      dockerfile: Dockerfile
    container_name: desafio_techlead_back
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN}
    networks:
      - public_network
      - private_network

  frontend:
    build:
      context: ./desafio_techlead_front
      dockerfile: Dockerfile
    container_name: desagio_techlead_front
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge

volumes:
  postgres_data: